---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: myapp-go
spec:
  encryptedData:
    DB_PASSWORD: AgAXj5UkK3RTPlZa2UinLZrFLMze6IRLj01yC3Jv0WpV8Jv3jXUKmV8G9TZCEkDZroUMpG3kOz8OKtBkqRVH34T2eNEC4SXLwzX9rh4XQlIP8X36lBE5GAeS98MtJiLU+kr2ay25od5hg0NjvBMaPkgl7lFGMTua/iVgrlTXmLLw7u4o8jrO65gT+pfVcJD+ayjgXgUfVOyGKHrYtSrKAWZP3Un8hLF1EPqi4mGDYetLJkX/QwmahXBbrxMfS3A0AFpv/b2JTL4WxBqHeviYECH0tLh9rtX2J6CvWQ8VbKu0Q97yfRyPikV+aDdoQq4Ome2uoyBU9dR1bJ/ts0mE31WEBEI3cuOM3DMqDRO/6tTIrHOmI1h2Cch41FihD1f6/R8fwSClFJ7B0Cb9Sn6yVd9kEreMnKLXoRfzaMvMGCVvxQ1oS45IqeR5t/S7cg9G36RyV2KaG8GfCBU5VE+VfRyFUkyBuNTau7KFlMxX6wShMscREet+uYnSb9NXu3lgE+0MHQcX14sJ3qJSq11mO3t14kqphP9nBsXEgIUNKFl26TXBbq2wz0eIMzDLPdVX5swq6yYN3mBysAcGIjzqM6TkNKvC+MD1cHcZHzbM46Yvp0BvoXT089q5Ih2lacTgvkgU7l+l2PcQiP8ibh5uxqDLbBrmJ7t87RlEWstdO/ynP/tURn3yW9gUz6M4vb5/A6/6NRUmUvFyPELOaO2Q7w==
    DB_USERNAME: AgC4IDPDd9gLWFjLvMhpC6AsEtK97wCNT8R0Ht4wnlygllzp6K7WCQ1sbiSwZDjnGT9PXGqcNg/mtNiHfRH8PqUYiPZd3KZ/xcufHdWZ10zw7sTjPs0z84TWkLwSjhbph70tNCcLB/A4S1EfghtKwg3lfEg06+/pNq8DwZuhSTjVv4/w5+D+P5tJT5SZ2j7IRp44Hpsnd0qnRxZyV3c5tsCmqFeTU/FFDaBWEDBOKW87mo+N9hXH0IqBuGq0GHumgCxL1SToXzqvVBoYrR77DtRDyr5vyiQo1TrkilBJA3dA3K5sVWpiY/SOItil9R/xEAZuWLQcA838sFuLEbdG29YHg2rRJn+CIYwH0yG5CRTWbnCYiGLC4MjoRf/Tt2gTBBhgGq/pv4NVipIDW4t+PCZZNAZNBjdJ6HV4cyHFUtz+2Dq05SMVFLzjrmTdQvyXD3LlyfiYLi2fwSHYD5GncyY0Sw68Mmf/hO91hsYhdmluX67vwqzphAdiWXJ6DETNiBEIPJH0EgH0UlnBfstDZOmdyNgTSTS3SLAVli+zOn52D3VDs+Q2ih21bHwaKZy3+jhB0O8dg5UDtGMDH7XIkntCiOJ5eiEWCro6amm3D06NRz+Xm7Zct8bJdUTp7zoANbOoqj50NulzUocjcdZGu+Twv4BXba1wBByx81G6Jk8BMUiVn/JZImb0R4RP6hUCBmM86T17
  template:
    metadata:
      name: app-secret
      namespace: myapp-go
