---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysql-secret
  namespace: mydb
spec:
  encryptedData:
    MYSQL_PASSWORD: AgByCU96hw9/vYSMYFVYGkPA8jheRRaCY7Y1tHd3DLyxTtz4ggx2fBBytXyNfFbXhNMkE86yJec4+igvHQYQfWFGof540T0PRvNLwf0oG+Q7MjTVP3842/FwWEMKvy3lJ7xP4DnXpd+qU/stRhm1RDF4NM0NASIDYY5zkkYkZ/Bes9Sa1ZZDLRmekntkoxKh5LRui3KS3G138wH4mBU8G8U+N6WICwNhPFlfgcadpKNkniLkM08bqKqbCvrX9YFhjujAODmJHL/bHxYm9uhdJAsf7+LEeEKAhcixrzUFCDaarwPpi5gpn72ljutCEjaVQD4l/3uzeKv+2jmXbhU1P0tFOlehsgzZRRcz7su5sW8Xcr5ehjL0RRZsttpWtlrNa/zHgqGNbCtA1va3mcfHRYEBm8/e+2yLG/NIxli4IEXiJBmMTgD210xGZiuXMWK9TBV4SQPkTp1RRXsPVsXZehMDTv6zeaRJ12AVBIYaR8E5g0VC7gRGCMnHuKrMq32acn71fC0Qz5KRb/QbUwG0e2zqv3HDdgoXSl9wFDebBlgU+nvqKxqV5IV2DmeUss25jBMx7fkG+UF1dnRCjvewWYe0DdWUl/1e8nClLPHKLnAzLPtw0qHhO9I7xrY8uIxojTEBIFjDFo8I8uzZDsDkLe+BpEpyZQO3++vDo1E2JqoswleqdJ4pzpBI1bAC+GxgfDyUYJiXerAESltmXwc=
    MYSQL_ROOT_PASSWORD: AgAYWR4Z7+I7lFZkcVvx4uxvCM14mvoOejRZouf8x5ojCHhw5sHT5jl7BD6xNiTihe237x4ARPbB8tCk9YkQsUvx+Y/MNZzXijLOSyHxpWZBnyiGGCc5plY5STCfA8K0srNcNR4Dbw5rvKrIB4Usk+Sflt3cV/WQ7ZDreXkgLRmIw9rCVsccHVmd2zdYqRhUbpAClJ08V2tODx9ZIpbCl5nrgThvdJXnePlzUKy2fGiA9CGrmYma6XK9DhIRmcyMNwVEjdzGEi4q4MhCW2wqI8Gcbl8GoREnFSLuK5r2wVv5AiLcnqjcn6+Q96+flIdyC+vx/Sbrvl/h5GO/w9THzPncGPjyMvngogJlF3BUs39wHkC7G515oHoEzdAyGpPf6drw5m6i0s1FvG5l+dsCb+whuDzWTHYfK9cMm9m9v5YJOe96yH4LHxV3VLsp8aT9zGdhSdMLCqzktGqFFJrFDTOQ2H/0J2wat0CFaOwvkrugsc5SBNXSpeEOuzrFkiyGP9+CtxR+FRRkFgHOxHYWKoG9th0udB+v+P32QGnRvltFNxuym9SKLwwS6OosFE3nVFtHnAFfjol54yXW9A7bwlS6QyuZREwaD+UOKFLEV9okyPCZSx17uMrCY1W2ILPZaZ0q2XnLv+KggR8+3Fv7lUa2vFOWpH+asVJ48YTJU5O2adAwLThPIgr9gQy7+NSKXcPPZM+O66zlKHBTHSpuug==
  template:
    metadata:
      name: mysql-secret
      namespace: mydb
