---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-go

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: myapp-go
data:
  DB_HOST: "mysql.mydb.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "test"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector-svc.observability.svc.cluster.local:4317"
  OTEL_EXPORTER_OTLP_INSECURE: "true"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: myapp-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-go
  template:
    metadata:
      labels:
        app: myapp-go
    spec:
      containers:
      - name: myapp-go
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128M
        image: localhost/tesseract/myapp-go:v1.0.1-5a24eb4
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DB_PASSWORD
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
        - name: OTEL_EXPORTER_OTLP_INSECURE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: OTEL_EXPORTER_OTLP_INSECURE

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: myapp-go
spec:
  selector:
    app: myapp-go
  ports:
  - protocol: TCP
    port: 8003
    targetPort: 8003
  type: ClusterIP
