apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app.yaml
  - mysql.yaml
  - elasticsearch/elasticsearch.yaml
  - jaegar/jaegar.yaml
  - otel-collector/otel-collector.yaml

secretGenerator:
  - name: mysql-secret
    namespace: mydb
    envs:
      - secrets/mysql.env
  - name: app-secret
    namespace: myapp-go
    envs:
      - secrets/app.env

generatorOptions:
  disableNameSuffixHash: true
